# Generated by Django 4.0.1 on 2022-01-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'حواله ورود',
                'verbose_name_plural': 'حواله های ورود',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=300, verbose_name='بابت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'حواله خروج',
                'verbose_name_plural': 'حواله های خروج',
            },
        ),
        migrations.CreateModel(
            name='OutputDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار خروجی')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.output', verbose_name='حواله خروج')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزییات حواله خروج',
                'verbose_name_plural': 'جزییات های حواله خروج',
            },
        ),
        migrations.CreateModel(
            name='InputDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار ورودی')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.input', verbose_name='حواله ورود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزییات حواله ورود',
                'verbose_name_plural': 'جزییات های حواله ورود',
            },
        ),
    ]
