# Generated by Django 4.0.1 on 2022-01-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_store_temp1_remove_store_temp2'),
        ('bills', '0002_alter_input_options_alter_output_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdetail',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='stores.store', verbose_name='انبار'),
            preserve_default=False,
        ),
    ]
