# Generated by Django 4.0.1 on 2022-01-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_outputdetail_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputdetail',
            name='store',
        ),
    ]
