# Generated by Django 4.0.1 on 2022-01-17 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('site_url', models.URLField(verbose_name='آدرس دامنه سایت')),
                ('short_des', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('email', models.EmailField(max_length=100, verbose_name='پست الکترونیک')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
                ('copy_right', models.TextField(blank=True, null=True, verbose_name='متن کپی رایت')),
                ('logo_image', models.FileField(blank=True, null=True, upload_to='settings/', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])], verbose_name='تصویر لوگو')),
                ('fav_icon', models.FileField(blank=True, null=True, upload_to='settings/', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])], verbose_name='فاوآیکون')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='عکس')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.sitesettings', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'عکس پس زمینه',
                'verbose_name_plural': 'عکس های پس زمینه',
            },
        ),
    ]
