# Generated by Django 4.0.1 on 2022-01-19 04:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='temp1',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='جلالی 1'),
        ),
        migrations.AddField(
            model_name='store',
            name='temp2',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='جلالی 2'),
        ),
    ]
