# Generated by Django 4.0.1 on 2022-01-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_temp1_store_temp2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='temp1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='temp2',
        ),
    ]
